// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/auth-svc.proto

package authsvc

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AuthSvc service

func NewAuthSvcEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AuthSvc service

type AuthSvcService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (AuthSvc_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (AuthSvc_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (AuthSvc_BidiStreamService, error)
}

type authSvcService struct {
	c    client.Client
	name string
}

func NewAuthSvcService(name string, c client.Client) AuthSvcService {
	return &authSvcService{
		c:    c,
		name: name,
	}
}

func (c *authSvcService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "AuthSvc.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSvcService) ClientStream(ctx context.Context, opts ...client.CallOption) (AuthSvc_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "AuthSvc.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &authSvcServiceClientStream{stream}, nil
}

type AuthSvc_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type authSvcServiceClientStream struct {
	stream client.Stream
}

func (x *authSvcServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *authSvcServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *authSvcServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authSvcServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authSvcServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authSvcServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *authSvcService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (AuthSvc_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "AuthSvc.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &authSvcServiceServerStream{stream}, nil
}

type AuthSvc_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type authSvcServiceServerStream struct {
	stream client.Stream
}

func (x *authSvcServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *authSvcServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *authSvcServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authSvcServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authSvcServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authSvcServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authSvcService) BidiStream(ctx context.Context, opts ...client.CallOption) (AuthSvc_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "AuthSvc.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &authSvcServiceBidiStream{stream}, nil
}

type AuthSvc_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type authSvcServiceBidiStream struct {
	stream client.Stream
}

func (x *authSvcServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *authSvcServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *authSvcServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authSvcServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authSvcServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authSvcServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *authSvcServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for AuthSvc service

type AuthSvcHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, AuthSvc_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, AuthSvc_ServerStreamStream) error
	BidiStream(context.Context, AuthSvc_BidiStreamStream) error
}

func RegisterAuthSvcHandler(s server.Server, hdlr AuthSvcHandler, opts ...server.HandlerOption) error {
	type authSvc interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type AuthSvc struct {
		authSvc
	}
	h := &authSvcHandler{hdlr}
	return s.Handle(s.NewHandler(&AuthSvc{h}, opts...))
}

type authSvcHandler struct {
	AuthSvcHandler
}

func (h *authSvcHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.AuthSvcHandler.Call(ctx, in, out)
}

func (h *authSvcHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.AuthSvcHandler.ClientStream(ctx, &authSvcClientStreamStream{stream})
}

type AuthSvc_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type authSvcClientStreamStream struct {
	stream server.Stream
}

func (x *authSvcClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *authSvcClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authSvcClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authSvcClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authSvcClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *authSvcHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AuthSvcHandler.ServerStream(ctx, m, &authSvcServerStreamStream{stream})
}

type AuthSvc_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type authSvcServerStreamStream struct {
	stream server.Stream
}

func (x *authSvcServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *authSvcServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authSvcServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authSvcServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authSvcServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *authSvcHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.AuthSvcHandler.BidiStream(ctx, &authSvcBidiStreamStream{stream})
}

type AuthSvc_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type authSvcBidiStreamStream struct {
	stream server.Stream
}

func (x *authSvcBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *authSvcBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authSvcBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authSvcBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authSvcBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *authSvcBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
